### ISSUE TITLE
Import redmine issues

### ISSUE THREAD

**Issue by Totopolis** [Totopolis/Kamban#2]
1. Separate tab
2. Input rm credentials
3. Select projetc & artefacts

**Comment by BerndGit** [comment]
@Totopolis:   I'm not sure if you are aware that some coding work regarding redmine is already done in the branch feature/refactoring by @Liklainy   see: https://github.com/Totopolis/Kamban/commit/11ad03dbf9bb0585e317ca9bb0fdcb81b0381da7
Since I don't have redmine installed, I cannot check the maturity of this implementation.
